FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    git \
    git-lfs \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN git lfs install && git lfs pull
# Port for Streamlit
EXPOSE 8501

# For uploaded video/image frontend
CMD ["streamlit", "run", "app/streamlit-app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

# For webcam frontend
# CMD ["streamlit", "run", "app/streamlit-webcam.py", "--server.port", "8502", "--server.address", "0.0.0.0"]