FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    git \
    git-lfs \
    && rm -rf /var/lib/apt/lists/*
COPY requirements-backend.txt .

ARG USE_GPU=false
RUN --mount=type=cache,target=/root/.cache/pip \
    if [ "$USE_GPU" = "false" ] ; then \
    pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu ; \
    fi

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements-backend.txt
COPY . .

RUN git lfs install && git lfs pull
# Port for FastAPI
EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
